# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playtimeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_playtimeEdit(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(405, 284)
        Form.setMinimumSize(QtCore.QSize(405, 284))
        Form.setMaximumSize(QtCore.QSize(405, 284))
        self.name1 = QtWidgets.QLineEdit(Form)
        self.name1.setGeometry(QtCore.QRect(220, 60, 161, 20))
        self.name1.setObjectName("name1")
        self.name2 = QtWidgets.QLineEdit(Form)
        self.name2.setGeometry(QtCore.QRect(220, 90, 161, 20))
        self.name2.setObjectName("name2")
        self.name3 = QtWidgets.QLineEdit(Form)
        self.name3.setGeometry(QtCore.QRect(220, 120, 161, 20))
        self.name3.setObjectName("name3")
        self.name4 = QtWidgets.QLineEdit(Form)
        self.name4.setGeometry(QtCore.QRect(220, 150, 161, 20))
        self.name4.setObjectName("name4")
        self.name5 = QtWidgets.QLineEdit(Form)
        self.name5.setGeometry(QtCore.QRect(220, 180, 161, 20))
        self.name5.setObjectName("name5")
        self.name6 = QtWidgets.QLineEdit(Form)
        self.name6.setGeometry(QtCore.QRect(220, 210, 161, 20))
        self.name6.setObjectName("name6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 47, 21))
        self.label.setObjectName("label")
        self.time1 = QtWidgets.QTimeEdit(Form)
        self.time1.setGeometry(QtCore.QRect(70, 60, 51, 22))
        self.time1.setObjectName("time1")
        self.time2 = QtWidgets.QTimeEdit(Form)
        self.time2.setGeometry(QtCore.QRect(70, 90, 51, 22))
        self.time2.setObjectName("time2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 47, 21))
        self.label_2.setObjectName("label_2")
        self.time3 = QtWidgets.QTimeEdit(Form)
        self.time3.setGeometry(QtCore.QRect(70, 120, 51, 22))
        self.time3.setObjectName("time3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 47, 21))
        self.label_3.setObjectName("label_3")
        self.time4 = QtWidgets.QTimeEdit(Form)
        self.time4.setGeometry(QtCore.QRect(70, 150, 51, 22))
        self.time4.setObjectName("time4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 47, 21))
        self.label_4.setObjectName("label_4")
        self.time5 = QtWidgets.QTimeEdit(Form)
        self.time5.setGeometry(QtCore.QRect(70, 180, 51, 22))
        self.time5.setObjectName("time5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 47, 21))
        self.label_5.setObjectName("label_5")
        self.time6 = QtWidgets.QTimeEdit(Form)
        self.time6.setGeometry(QtCore.QRect(70, 210, 51, 22))
        self.time6.setObjectName("time6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 47, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(146, 60, 61, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(146, 92, 61, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(146, 122, 61, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(146, 150, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(146, 180, 61, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(146, 210, 61, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(150, 0, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Playtime Edit"))
        self.label.setText(_translate("Form", "Time 1"))
        self.label_2.setText(_translate("Form", "Time 2"))
        self.label_3.setText(_translate("Form", "Time 3"))
        self.label_4.setText(_translate("Form", "Time 4"))
        self.label_5.setText(_translate("Form", "Time 5"))
        self.label_6.setText(_translate("Form", "Time 6"))
        self.label_7.setText(_translate("Form", "Movie Name"))
        self.label_8.setText(_translate("Form", "Movie Name"))
        self.label_9.setText(_translate("Form", "Movie Name"))
        self.label_10.setText(_translate("Form", "Movie Name"))
        self.label_11.setText(_translate("Form", "Movie Name"))
        self.label_12.setText(_translate("Form", "Movie Name"))
        self.label_13.setText(_translate("Form", "ROUNDEDIT"))
        self.pushButton.setText(_translate("Form", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

