# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrationForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegistratioForm(object):
    def setupUi(self, RegistratioForm):
        RegistratioForm.setObjectName("RegistratioForm")
        RegistratioForm.resize(400, 430)
        self.usrLbl = QtWidgets.QLabel(RegistratioForm)
        self.usrLbl.setGeometry(QtCore.QRect(60, 90, 47, 16))
        self.usrLbl.setObjectName("usrLbl")
        self.pwLbl = QtWidgets.QLabel(RegistratioForm)
        self.pwLbl.setGeometry(QtCore.QRect(20, 150, 91, 16))
        self.pwLbl.setObjectName("pwLbl")
        self.nameLbl = QtWidgets.QLabel(RegistratioForm)
        self.nameLbl.setGeometry(QtCore.QRect(80, 180, 31, 16))
        self.nameLbl.setObjectName("nameLbl")
        self.dobLbl = QtWidgets.QLabel(RegistratioForm)
        self.dobLbl.setGeometry(QtCore.QRect(50, 210, 61, 16))
        self.dobLbl.setObjectName("dobLbl")
        self.userIn = QtWidgets.QLineEdit(RegistratioForm)
        self.userIn.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.userIn.setObjectName("userIn")
        self.passwordConInput = QtWidgets.QLineEdit(RegistratioForm)
        self.passwordConInput.setGeometry(QtCore.QRect(120, 150, 113, 20))
        self.passwordConInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordConInput.setObjectName("passwordConInput")
        self.nameIn = QtWidgets.QLineEdit(RegistratioForm)
        self.nameIn.setGeometry(QtCore.QRect(120, 180, 81, 20))
        self.nameIn.setObjectName("nameIn")
        self.lastIn = QtWidgets.QLineEdit(RegistratioForm)
        self.lastIn.setGeometry(QtCore.QRect(260, 180, 81, 20))
        self.lastIn.setObjectName("lastIn")
        self.lastnameLbl = QtWidgets.QLabel(RegistratioForm)
        self.lastnameLbl.setGeometry(QtCore.QRect(210, 180, 47, 20))
        self.lastnameLbl.setObjectName("lastnameLbl")
        self.dateofbirthin = QtWidgets.QDateEdit(RegistratioForm)
        self.dateofbirthin.setDisplayFormat("dd-MMM-yyyy")
        self.dateofbirthin.setGeometry(QtCore.QRect(120, 210, 110, 22))
        self.dateofbirthin.setObjectName("dateofbirthin")
        self.pushButton = QtWidgets.QPushButton(RegistratioForm)
        self.pushButton.setGeometry(QtCore.QRect(50, 360, 301, 31))
        self.pushButton.setObjectName("pushButton")
        self.addressInput = QtWidgets.QTextEdit(RegistratioForm)
        self.addressInput.setGeometry(QtCore.QRect(120, 240, 221, 61))
        self.addressInput.setObjectName("addressInput")
        self.addrLbl = QtWidgets.QLabel(RegistratioForm)
        self.addrLbl.setGeometry(QtCore.QRect(50, 240, 47, 13))
        self.addrLbl.setObjectName("addrLbl")
        self.zipIn = QtWidgets.QLineEdit(RegistratioForm)
        self.zipIn.setGeometry(QtCore.QRect(120, 310, 71, 20))
        self.zipIn.setText("")
        self.zipIn.setObjectName("zipIn")
        self.zipLbl = QtWidgets.QLabel(RegistratioForm)
        self.zipLbl.setGeometry(QtCore.QRect(50, 310, 47, 13))
        self.zipLbl.setObjectName("zipLbl")
        self.topLabel = QtWidgets.QLabel(RegistratioForm)
        self.topLabel.setGeometry(QtCore.QRect(90, 10, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.topLabel.setFont(font)
        self.topLabel.setObjectName("topLabel")
        self.backGround = QtWidgets.QLabel(RegistratioForm)
        self.backGround.setGeometry(QtCore.QRect(0, 0, 401, 431))
        self.backGround.setText("")
        self.backGround.setObjectName("backGround")
        self.pwLbl_2 = QtWidgets.QLabel(RegistratioForm)
        self.pwLbl_2.setGeometry(QtCore.QRect(60, 120, 47, 13))
        self.pwLbl_2.setObjectName("pwLbl_2")
        self.passwordInput = QtWidgets.QLineEdit(RegistratioForm)
        self.passwordInput.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.backGround.raise_()
        self.usrLbl.raise_()
        self.pwLbl.raise_()
        self.nameLbl.raise_()
        self.dobLbl.raise_()
        self.userIn.raise_()
        self.passwordConInput.raise_()
        self.nameIn.raise_()
        self.lastIn.raise_()
        self.lastnameLbl.raise_()
        self.dateofbirthin.raise_()
        self.pushButton.raise_()
        self.addressInput.raise_()
        self.addrLbl.raise_()
        self.zipIn.raise_()
        self.zipLbl.raise_()
        self.topLabel.raise_()
        self.pwLbl_2.raise_()
        self.passwordInput.raise_()

        self.retranslateUi(RegistratioForm)
        QtCore.QMetaObject.connectSlotsByName(RegistratioForm)

    def retranslateUi(self, RegistratioForm):
        _translate = QtCore.QCoreApplication.translate
        RegistratioForm.setWindowTitle(_translate("RegistratioForm", "Form"))
        self.usrLbl.setText(_translate("RegistratioForm", "Username"))
        self.pwLbl.setText(_translate("RegistratioForm", "Confirm Password"))
        self.nameLbl.setText(_translate("RegistratioForm", "Name"))
        self.dobLbl.setText(_translate("RegistratioForm", "Date of Birth"))
        self.lastnameLbl.setText(_translate("RegistratioForm", "Lastname"))
        self.pushButton.setText(_translate("RegistratioForm", "Register"))
        self.addrLbl.setText(_translate("RegistratioForm", "Address"))
        self.zipLbl.setText(_translate("RegistratioForm", "ZIP Code"))
        self.topLabel.setText(_translate("RegistratioForm", "REGISTER"))
        self.pwLbl_2.setText(_translate("RegistratioForm", "Password"))
